### ISSUE TITLE
typo **动作方法 (Action method) ** -> **动作方法 (Action method)**

### ISSUE THREAD

**Issue by logicshan** [WangXuan95/BSV_Tutorial_cn#14]
https://github.com/WangXuan95/BSV_Tutorial_cn/blob/0df1a11e3f765de61824226ab78e84f8b6a4c72b/README.md?plain=1#L3170

**Comment by WangXuan95** [comment]
非常感谢您给我提出各种笔误，您可以统一改正并给本库提交 pull request ，这样您也可以成为本库的贡献者之一。如果不想提交 pull request 那我稍后会统一改正。
