### ISSUE TITLE
TLog#(n)

### ISSUE THREAD

**Issue by logicshan** [WangXuan95/BSV_Tutorial_cn#18]
https://github.com/WangXuan95/BSV_Tutorial_cn/blob/0df1a11e3f765de61824226ab78e84f8b6a4c72b/README.md?plain=1#L5567

bsv-reference-guide 中
Log#(n1,n2)  // Meaning: assert ceiling(log(n1)) = n2

这里说"至少"，似乎不太明确。

还有下面 TLog#(n)

bsv-reference-guide 中
TLog#(n1)  // Calculate ceiling log2(n1)

按照 log2(n-1)+1 计算的话

表 21 中，n 的值等于 1 的时候，结果似乎不对

**Comment by WangXuan95** [comment]
你好， log2(n-1)+1 其实就相当于 ceil(log2(n)) ，其中 ceil 是向上取整。但在 1 这个特殊值的时候不对。我已改成更容易理解的 ceil(log2(n)) 这个说法。
另外，我改成了这种说法： ceil(log2(n)) 代表 n-1 这个数字的二进制表示需要多少个 bit 。 这样似乎更容易理解
