### ISSUE TITLE
这里TestWire注释是否为笔误

### ISSUE THREAD

**Issue by zephray** [WangXuan95/BSV_Tutorial_cn#2]
https://github.com/WangXuan95/BSV_Tutorial_cn/blob/dbd15f4498e2db42bbde38b00d27a9420c5f15a0/README.md?plain=1#L1953

这行注释 ```// 只能在 w1._read 和 w2._write 的周期激活``` 是否应该是 ```// 只能在 w1._read 和 w2._read 的周期激活``` 还是我理解有误？

谢谢

**Comment by WangXuan95** [comment]
是我的笔误，将在下次commit时修正
